[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
async-trait = "0.1.82"
clap = "4.5.20"
itertools = "0.13.0"

chrono = "0.4.38"
miette = "7.2.0"
reqwest = "0.12.5"
reqwest-middleware = "0.3.2"
tokio = "1.37.0"
tempfile = "3.10.1"
clap-verbosity-flag = "2.2.1"
tracing-subscriber = "0.3.18"
serde_yaml = "0.9.33"
serde = "1.0"
minijinja = "2.3.0"

parking_lot = "0.12.3"

jsonrpc-stdio-server = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-core = "18.0.0"

rattler-build = { git = "https://github.com/nichmor/rattler-build", branch = "feat/pixi-build", default-features = false }
# rattler_conda_types = "0.28.2"
rattler_package_streaming = "0.22.10"
# rattler_virtual_packages = "1.1.7"

file_url = "0.1.4"
rattler = { version = "0.28.1", default-features = false }
rattler_cache = { version = "0.2.9", default-features = false }
rattler_conda_types = { version = "0.29.1", default-features = false }
rattler_digest = { version = "1.0.3", default-features = false }
rattler_lock = { version = "0.22.30", default-features = false }
rattler_networking = { version = "0.21.5", default-features = false, features = [
  "google-cloud-auth",
] }
rattler_repodata_gateway = { version = "0.21.21", default-features = false }
rattler_shell = { version = "0.22.6", default-features = false }
rattler_solve = { version = "1.2.2", default-features = false }
rattler_virtual_packages = { version = "1.1.9", default-features = false }

# rattler = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_conda_types = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_digest = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_lock = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_networking = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_package_streaming = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_repodata_gateway = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_shell = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_solve = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
# rattler_virtual_packages = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }

#pixi_build_types = { path = "../pixi-build-branch/crates/pixi_build_types" }
#pixi_consts = { path = "../pixi-build-branch/crates/pixi_consts" }
#pixi_manifest = { path = "../pixi-build-branch/crates/pixi_manifest" }
#pixi_spec = { path = "../pixi-build-branch/crates/pixi_spec" }

pixi_build_types = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }
pixi_consts = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }
pixi_manifest = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }
pixi_spec = { git = "https://github.com/prefix-dev/pixi", branch = "feature/pixi-build" }


[patch.crates-io]
file_url = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_conda_types = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_digest = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_lock = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_networking = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_package_streaming = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_repodata_gateway = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_shell = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_solve = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
rattler_virtual_packages = { git = "https://github.com/conda/rattler", branch = "feat/pixi-build" }
