recipe:
  name: pixi-build
  version: "0.0.1"

source:
  path: .

cache:
  requirements:
    build:
      - ${{ compiler("rust") }}
    host:
      - xz >=5.0, <6.0
      - if: unix
        then: openssl

  build:
    script:
      - if: unix
        then:
          - cargo install --locked --root $PREFIX --path crates/pixi-build --no-track --bins
        else:
          - cargo install --locked --root %PREFIX% --path crates/pixi-build --no-track --bins

outputs:
  - package:
      name: pixi-build-python
    build:
      files:
        if: unix
        then:
          - bin/pixi-build-python
        else:
          - bin/pixi-build-python.exe
    tests:
      - script:
          if: unix
          then:
            - pixi-build-python --help
          else:
            - pixi-build-python.exe --help
  - package:
      name: pixi-build-cmake
    build:
      files:
        if: unix
        then:
          - bin/pixi-build-cmake
        else:
          - bin/pixi-build-cmake.exe
    tests:
      - script:
          if: unix
          then:
            - pixi-build-cmake --help
          else:
            - pixi-build-cmake.exe --help
