on:
  push:
    branches:
      - "main"
  pull_request:

name: "Build Conda Package"

jobs:
  rattler-build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-20.04 }
          - { target: win-64, os: windows-latest }
          # force older macos-13 to get x86_64 runners
          - { target: osx-64, os: macos-13 }
          - { target: osx-arm64, os: macos-14 }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.32.1
          cache: true
          environments: build-self
      - name: Run rattler-build
        shell: bash
        env:
          TARGET_PLATFORM: ${{ matrix.target }}
        run: |
          pixi r -e build-self rattler-build build --output=$RUNNER_TEMP --target-platform=${{ env.TARGET_PLATFORM }} --no-include-recipe --experimental
